### DISCUSSION TITLE
Pick community mind

### DISCUSSION THREAD

**Discussion by maghazouani** [browser-use/workflow-use#55] [General]
Hello community, 

(I haven't tried it)
I'm thinking of a use case to open the CRM and add a contact. 
If I'll show the browser how to add a contact. Then from there the data will be dynamic ? meaning it won't leverage the same data used for the recording ? 

Thanks
Mahdi G

**Comment by Cfomodz** [comment]
**Yes, the data will be dynamic!** Workflow-use is specifically designed to record a workflow once and then reuse it with different data each time. The system automatically extracts variables from forms and allows you to provide new values for each execution.

## How Dynamic Data Works in Workflow-Use

### Variables and Input Schema

When you record a workflow (like adding a contact to your CRM), workflow-use automatically:

1. **Detects form fields** during the recording
2. **Creates variables** using the `{variable_name}` syntax
3. **Generates an input schema** that defines what data is needed

Example from the repository:

```yaml
steps:
- description: Enter first name
  type: input
  target_text: firstName
  value: '{first_name}'
- description: Enter last name
  type: input
  target_text: lastName
  value: '{last_name}'

input_schema:
- name: first_name
  type: string
  required: true
- name: last_name
  type: string
  required: true
```

### For Your CRM Use Case

When you record adding a contact to your CRM:

1. **Record once** - Show the browser how to navigate to the CRM and add a contact with example data
2. **Variables are extracted** - The system identifies input fields (name, email, phone, etc.)
3. **Reuse with new data** - Each subsequent execution uses different contact information

### Two Ways to Run with Dynamic Data

#### Method 1: Interactive CLI
```bash
python cli.py run-workflow-no-ai add_crm_contact.workflow.json
```
The CLI will prompt you for each variable:
```
Enter value for contact_name (required, type: string): John Smith
Enter value for contact_email (required, type: string): john@example.com
```

#### Method 2: Programmatic API
```python
from workflow_use import Workflow

workflow = Workflow.load_from_file("add_crm_contact.workflow.json")
result = await workflow.run_with_no_ai(
    input_values={
        "contact_name": "Jane Doe",
        "contact_email": "jane@example.com",
        "contact_phone": "+1-555-0123"
    }
)
```

###  Run as Tool (AI-Powered Flexibility)

You can also run workflows as tools with natural language prompts:

```bash
python cli.py run-as-tool add_crm_contact.workflow.json --prompt "add a contact named Alice Cooper with email alice@rock.com"
```

The LLM will extract the data from your prompt and map it to the workflow variables.
